# Experiment plan configuration
experiment_name: "5_layers_decrease_mid_symmetric"

# Base configuration (will be used for all experiments)
base_config:
  problem: schrodinger
  activation: tanh
  epochs: 2000
  batch_size: 512
  lr: 0.0001
  cuda: true
  eval_only: false
  resume_from: null
  bins: 5
  print_every: 200
  save_every: 500
  ncc_eval_every: 400
  seed: 42
  
  # Problem-specific domains and loss weights
  schrodinger:
    spatial_dim: 1
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 1.5707963267948966]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  problem2:
    spatial_dim: 1
    spatial_domain: [[0.0, 1.0]]
    temporal_domain: [0.0, 1.0]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  # Dataset sizes
  n_residual_train: 20000
  n_initial_train: 50
  n_boundary_train: 50
  n_residual_eval: 1000
  n_initial_eval: 20
  n_boundary_eval: 20
  n_samples_ncc: 5000

# Experiments to run (only architecture varies)
experiments:  
  - name: "1_mid_layer_50"
    architecture: [2, 100, 100, 50, 100, 100, 2]

  - name: "1_mid_layer_75"
    architecture: [2, 100, 100, 75, 100, 100, 2]

  - name: "1_mid_layer_25"
    architecture: [2, 100, 100, 25, 100, 100, 2]
  
  - name: "3_mid_layer_50"
    architecture: [2, 100, 50, 50, 50, 100, 2]

  - name: "decreasing_mid_layer_to_50"
    architecture: [2, 100, 75, 50, 75, 100, 2]

  - name: "decreasing_mid_layer_to_25"
    architecture: [2, 100, 50, 25, 50, 100, 2]
