# Experiment plan configuration
experiment_name: "Burgers2d_convergence_test"

# Base configuration (will be used for all experiments)
base_config:
  problem: burgers2d
  activation: tanh
  epochs: 10000
  batch_size: 512
  lr: 0.0001
  
  # Optimizer settings
  optimizer_switch_at: 0.9
  
  # Adam hyperparameters
  adam_betas: [0.9, 0.999]
  adam_eps: 1.0e-8
  
  # LBFGS hyperparameters
  lbfgs_lr: 1.0
  lbfgs_max_iter: 20
  lbfgs_history_size: 20
  lbfgs_line_search: 'strong_wolfe'
  lbfgs_tolerance_grad: 0.0  # Set to 0 to disable gradient-based convergence check
  lbfgs_tolerance_change: 0.0  # Set to 0 to disable loss change convergence check
  
  cuda: true
  eval_only: false
  resume_from: null
  bins: 5
  n_bin_visualize_ncc: 100
  eval_every: 500
  print_every: 1000
  save_every: 5000
  inner_metrics_eval_every: 2501
  seed: 42
  
  # Problem-specific domains and loss weights
  schrodinger:
    spatial_dim: 1
    output_dim: 2  # Complex-valued: h = [u, v]
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 1.5707963267948966]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  wave1d:
    spatial_dim: 1
    output_dim: 1  # Real-valued: h is scalar
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 6.283185307179586]  # 2Ï€
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  burgers1d:
    spatial_dim: 1
    output_dim: 1  # Real-valued: h is scalar
    spatial_domain: [[-1.0, 1.0]]
    temporal_domain: [0.0, 1.0]
    nu: 0.01  # Viscosity coefficient
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  burgers2d:
    spatial_dim: 2
    output_dim: 1  # Real-valued: h is scalar
    spatial_domain: [[0.0, 1.0], [0.0, 1.0]]
    temporal_domain: [0.0, 2.0]
    nu: 0.1  # Viscosity coefficient
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  problem2:
    spatial_dim: 1
    output_dim: 2
    spatial_domain: [[0.0, 1.0]]
    temporal_domain: [0.0, 1.0]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  # Dataset sizes
  n_residual_train: 20000
  n_initial_train: 100
  n_boundary_train: 100
  n_residual_eval: 5000
  n_initial_eval: 25
  n_boundary_eval: 25
  n_samples_ncc: 5000 

# Experiments to run (schrodinger test only)
experiments:

  - name: "3lyr_30k_Wn_flat"
    problem: burgers2d
    architecture: [3, 120, 120, 120, 1]

#  - name: "5lyr_30k_Wn_flat"
#    problem: burgers2d
#    architecture: [3, 8, 8, 8, 8, 8, 1]

#  - name: "7lyr_30k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 70, 70, 70, 70, 70, 70, 70, 1]

#  - name: "3lyr_20k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 100, 100, 100, 1]

#  - name: "5lyr_20k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 70, 70, 70, 70, 70, 1]

#  - name: "7lyr_20k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 58, 58, 58, 58, 58, 58, 58, 1]

#  - name: "3lyr_10k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 70, 70, 70, 1]

#  - name: "5lyr_10k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 50, 50, 50, 50, 50, 1]

#  - name: "7lyr_10k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 40, 40, 40, 40, 40, 40, 40, 1]

#  - name: "3lyr_5k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 46, 46, 46, 1]

#  - name: "5lyr_5k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 36, 36, 36, 36, 36, 1]

#  - name: "7lyr_5k_Wn_flat"
#    problem: burgers1d
#    architecture: [2, 28, 28, 28, 28, 28, 28, 28, 1]