# Experiment plan configuration
experiment_name: "schrodinger_capacity"

# Base configuration (will be used for all experiments)
base_config:
  problem: schrodinger
  activation: tanh
  epochs: 10000
  batch_size: 512
  lr: 0.0001
  
  # Optimizer settings
  optimizer_switch_at: 0.9
  
  # Adam hyperparameters
  adam_betas: [0.9, 0.999]
  adam_eps: 1.0e-8
  
  # LBFGS hyperparameters
  lbfgs_lr: 1.0
  lbfgs_max_iter: 20
  lbfgs_history_size: 20
  lbfgs_line_search: 'strong_wolfe'
  lbfgs_tolerance_grad: 0.0  # Set to 0 to disable gradient-based convergence check
  lbfgs_tolerance_change: 0.0  # Set to 0 to disable loss change convergence check
  
  cuda: true
  eval_only: false
  resume_from: null
  bins: 5
  n_bin_visualize_ncc: 100
  eval_every: 200
  print_every: 1000
  save_every: 5000
  inner_metrics_eval_every: 2501
  seed: 42
  
  # Problem-specific domains and loss weights
  schrodinger:
    spatial_dim: 1
    output_dim: 2  # Complex-valued: h = [u, v]
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 1.5707963267948966]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  wave1d:
    spatial_dim: 1
    output_dim: 1  # Real-valued: h is scalar
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 6.283185307179586]  # 2Ï€
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  problem2:
    spatial_dim: 1
    output_dim: 2
    spatial_domain: [[0.0, 1.0]]
    temporal_domain: [0.0, 1.0]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  # Dataset sizes
  n_residual_train: 20000
  n_initial_train: 100
  n_boundary_train: 100
  n_residual_eval: 5000
  n_initial_eval: 25
  n_boundary_eval: 25
  n_samples_ncc: 5000 

# Experiments to run (schrodinger test only)
experiments:  
  - name: "3lyr_40k_Wn_flat"
    problem: schrodinger
    architecture: [2, 140, 140, 140, 2]

  - name: "5lyr_40k_Wn_flat"
    problem: schrodinger
    architecture: [2, 100, 100, 100, 100, 100, 2]

  - name: "7lyr_40k_Wn_flat"
    problem: schrodinger
    architecture: [2, 80, 80, 80, 80, 80, 80, 80, 2]

  - name: "3lyr_30k_Wn_flat"
    problem: schrodinger
    architecture: [2, 120, 120, 120, 2]

  - name: "5lyr_30k_Wn_flat"
    problem: schrodinger
    architecture: [2, 85, 85, 85, 85, 85, 2]

  - name: "7lyr_30k_Wn_flat"
    problem: schrodinger
    architecture: [2, 70, 70, 70, 70, 70, 70, 70, 2]

  - name: "3lyr_20k_Wn_flat"
    problem: schrodinger
    architecture: [2, 100, 100, 100, 2]

  - name: "5lyr_20k_Wn_flat"
    problem: schrodinger
    architecture: [2, 70, 70, 70, 70, 70, 2]

  - name: "7lyr_20k_Wn_flat"
    problem: schrodinger
    architecture: [2, 58, 58, 58, 58, 58, 58, 58, 2]

  - name: "3lyr_10k_Wn_flat"
    problem: schrodinger
    architecture: [2, 70, 70, 70, 2]

  - name: "5lyr_10k_Wn_flat"
    problem: schrodinger
    architecture: [2, 50, 50, 50, 50, 50, 2]

  - name: "7lyr_10k_Wn_flat"
    problem: schrodinger
    architecture: [2, 40, 40, 40, 40, 40, 40, 40, 2]