activation: tanh
adam_betas:
- 0.9
- 0.999
adam_eps: 1.0e-08
adaptive_pinn:
  ANT_default_hidden_layers: 50
  ANT_threshold_architecture: null
  AToE_threshold_capacity: null
  base_everywhere: true
  base_weight: 0.3
  blending_mode: soft
  enable_gradient_diagnostics: false
  enable_timing: false
  enabled: true
  expert_activation_threshold: 0
  expert_type: resnet
  freeze_epochs_after_spawn: 400
  freeze_mode: none
  initial_train:
    epochs: 4000
  inner_metrics_calculation: false
  max_experts: 150
  perfect_trees_path: perfect_tree_examples/classic_norm/perfect_trees.json
  reinitialize_base_after_spawn: false
  relevant_samples_to_activate_expert: 0
  sigma_fraction: 0.2
  spawn_every_epochs: 4000
  spawn_plateau_delta: 0.01
  spawn_plateau_epochs: 300
  spawn_require_plateau: false
  spawning_method: full_tree_by_norm
  tree_max_depth: 15
  tree_min_samples_leaf: 50
  use_decomposed_derivatives: false
  variable_for_expert_size: norm
  variable_for_node_accept: norm
allen_cahn:
  D: 0.0001
  adaptive_sampling:
    phi: exponential
    phi_epsilon: 1.0
  causal_training:
    enabled: true
    min_weight_threshold: 0.99
    num_chunks: 32
    tol_schedule:
    - 0.01
    - 0.1
    - 1.0
    - 10.0
  fourier_features:
    scale: 3.0
  loss_weights:
    bc: 1.0
    ic: 100.0
    residual: 1.0
  new_norm_threshold: 0.04
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - -1.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.5
  wavelet_threshold: 0.002
base_architecture:
- 2
- 256
- 256
- 256
- 256
- 256
- 256
- 1
batch_size: 4096
bins: 5
burgers1d:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 0.015
  nu: 0.003141592653589793
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - -1.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.5
  wavelet_threshold: 0.001
burgers2d:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 0.015
  nu: 0.1
  output_dim: 1
  spatial_dim: 2
  spatial_domain:
  - - 0.0
    - 1.0
  - - 0.0
    - 1.0
  temporal_domain:
  - 0.0
  - 2.0
  tree_smoothness_threshold: 0.5
  wavelet_threshold: 0.0005
conv_diff:
  beta: 1.0
  epsilon: 0.01
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 0.05
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - -1.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.6
  wavelet_threshold: 0.005
cuda: true
epochs: 1
eval_every: 100
eval_only: false
fisher_kpp:
  D: 1.0
  kappa: 25.0
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 0.005
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - 0.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.6
  wavelet_threshold: 0.0005
fourier_features:
  dim: 128
  enabled: true
  scale: 2.0
git:
  git_branch: AToE-AToE-leaves-ANT
  git_commit: f53bdbb8c5ec98bcd9ff8a828b57dc7746983d58
  git_dirty: true
grad_clip_norm: null
init:
  hidden: glorot
  ls_use_bias: true
  output: ls
inner_metrics_eval_every: 1000
kdv:
  adaptive_sampling:
    phi: exponential
    phi_epsilon: 1.0
  causal_training:
    enabled: false
    min_weight_threshold: 0.99
    num_chunks: 50
    tol_schedule:
    - 0.1
    - 1.0
    - 10.0
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  mu: 0.000484
  new_norm_threshold: 0.2
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - -1.0
    - 1.0
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.4
  wavelet_threshold: 0.0025
ks:
  alpha: 6.25
  beta: 0.390625
  causal_training:
    enabled: false
    min_weight_threshold: 0.99
    num_chunks: 16
    tol_schedule:
    - 0.1
    - 1.0
    - 10.0
  fourier_features:
    scale: 2.0
  gamma: 0.00152587890625
  loss_weights:
    bc: 1.0
    ic: 10.0
    residual: 1.0
  new_norm_threshold: 10.0
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - 0.0
    - 6.283185307179586
  temporal_domain:
  - 0.0
  - 1.0
  tree_smoothness_threshold: 0.3
  wavelet_threshold: 0.04
lbfgs_history_size: 20
lbfgs_line_search: strong_wolfe
lbfgs_lr: 1.0
lbfgs_max_iter: 20
lbfgs_tolerance_change: 0.0
lbfgs_tolerance_grad: 0.0
lr: 0.001
lr_decay_rate: 0.9
lr_decay_steps: 2000
lr_schedule: exponential
lr_warmup_steps: 5000
lra:
  alpha: 0.1
  enabled: false
  update_every: 100
min_epochs: 1
model: AToE
n_bin_visualize_ncc: 100
n_freq_grid: 128
name: ks_resnet_adam_lbfgs
optimizer_1: adam
optimizer_2: lbfgs
optimizer_switch_epoch: 3000
patience_epochs: 50000
print_every: 100
problem: ks
resume_from: null
rwf: true
sampling:
  adaptive_sampling:
    adaptive_ratio: 0.1
    candidate_multiplier: 10
    enabled: false
  boundary_train_ratio: 0.026
  eval_train_ratio: 0.25
  initial_train_ratio: 0.026
  ncc_train_ratio: 0.25
  resample_every_epochs: 500
  sample_volume_ratio: 35
save_every: 1000
schrodinger:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 2.0
  output_dim: 2
  spatial_dim: 1
  spatial_domain:
  - - -5.0
    - 5.0
  temporal_domain:
  - 0.0
  - 1.5707963267948966
  tree_smoothness_threshold: 0.7
  wavelet_threshold: 0.1
seed: 42
soap_betas:
- 0.9
- 0.999
soap_precondition_frequency: 10
ssbroyden_history_size: 10
ssbroyden_line_search: strong-wolfe
ssbroyden_max_iter: 20
wave1d:
  loss_weights:
    bc: 1.0
    ic: 1.0
    residual: 1.0
  new_norm_threshold: 1.5
  output_dim: 1
  spatial_dim: 1
  spatial_domain:
  - - -5.0
    - 5.0
  temporal_domain:
  - 0.0
  - 6.283185307179586
  tree_smoothness_threshold: 0.35
  wavelet_threshold: 0.3
