# Experiment plan configuration
experiment_name: "40,000_params_linear_slope_vs_flat_7_layers"

# Base configuration (will be used for all experiments)
base_config:
  problem: schrodinger
  activation: tanh
  epochs: 10000
  batch_size: 512
  lr: 0.0001
  
  # Optimizer settings
  optimizer_switch_at: 0.9  # Switch from Adam to LBFGS at 90%
  
  # Adam hyperparameters
  adam_betas: [0.9, 0.999]
  adam_eps: 1.0e-8
  
  # LBFGS hyperparameters
  lbfgs_lr: 1.0
  lbfgs_max_iter: 20
  lbfgs_history_size: 20
  lbfgs_line_search: 'strong_wolfe'
  lbfgs_tolerance_grad: 0.000000000000001
  lbfgs_tolerance_change: 0.000000000000001
  
  cuda: true
  eval_only: false
  resume_from: null
  bins: 5
  print_every: 1000
  save_every: 5000
  ncc_eval_every: 3400
  seed: 42
  
  # Problem-specific domains and loss weights
  schrodinger:
    spatial_dim: 1
    spatial_domain: [[-5.0, 5.0]]
    temporal_domain: [0.0, 1.5707963267948966]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  problem2:
    spatial_dim: 1
    spatial_domain: [[0.0, 1.0]]
    temporal_domain: [0.0, 1.0]
    loss_weights:
      residual: 1.0
      ic: 1.0
      bc: 1.0
  
  # Dataset sizes
  n_residual_train: 20000
  n_initial_train: 50
  n_boundary_train: 50
  n_residual_eval: 1000
  n_initial_eval: 20
  n_boundary_eval: 20
  n_samples_ncc: 5000

# Experiments to run (only architecture varies)
experiments:  
  - name: "flat"
    architecture: [2, 80, 80, 80, 80, 80, 80, 80, 2]
  
  - name: "linear_slope_less_params"
    architecture: [2, 40, 80, 80, 80, 80, 80, 40, 2]
  
  - name: "linear_slope_same_params_same_layers"
    architecture: [2, 45, 90, 90, 90, 90, 90, 45, 2]

  - name: "linear_slope_same_params_more_layers"
    architecture: [2, 41, 82, 82, 82, 82, 82, 82, 41, 2]
